### PR TITLE
chore: Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
## Description
Hi, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/SimpSOM/) that can improve the general code quality here.
This PR fixes a few of the issues detected.

## Summary of changes
- Refactor iteration over dictionary.
- Use `with` statement to open file.
- Use `is` for comparison with `True` instead of `==`.
- Remove redundant imports.
- Add `.deepsource.toml` configuration file.

### CODE REVIEW

**Comment by fcomitani** [comment]
All looks in order. Thanks for this.

**Comment by akshgpt7** [comment]
@fcomitani, Thanks for merging this. I'd just like to point out that the issues fixed here were detected by running [DeepSource](https://deepsource.io/) analysis on the repo. If you like, you can activate analysis for your repository to detect such code quality issues/bug risks on the fly for every new change made before merging it. It significantly reduces code review time. You can also use the Autofix feature to fix them with one click.

If you wish to, here's how you can quickly activate DeepSource to continuously analyze your repository:
- Sign up on [DeepSource](https://deepsource.io/signup) and activate analysis for your repository.
- Create `.deepsource.toml` configuration which you can use to configure your analysis settings (This PR already added that, but you can edit it any time).
- Activate/Check your analysis [here](https://deepsource.io/gh/fcomitani/SimpSOM).

If you have any doubts or questions, you can check out the [docs](https:/deepsource.io/docs), or feel free to reach out :)

**Comment by akshgpt7** [comment]
@fcomitani  do you need any help with activating DeepSource?
I ask so because the `.deepsource.toml` file that you merged will only take effect if analysis is activated.

**Comment by fcomitani** [comment]
Hi @akshgpt7, thank you.
At the moment this part of the project is on hold since I have other priorities, but I will eventually get to it.
I'll make sure to ask for help if I need any in the future.

Thanks again.

**Pull request merged**
